# Generated by Django 5.0.3 on 2024-04-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image',
            new_name='image',
        ),
    ]
