# Generated by Django 5.0.3 on 2024-04-02 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='task.product'),
            preserve_default=False,
        ),
    ]
