# Generated by Django 5.0.3 on 2024-04-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_shop_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('change_student_name', 'can change the name of the student'),), 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
    ]
