# Generated by Django 5.0.3 on 2024-04-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_category_parents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('change_category_features', 'change things related to Category')], 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_product_features', 'change things related to Product')]},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'permissions': [('change_image_of_product_features', 'change things related to ProductImage')]},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': [('change_shop_features', 'change things related to Shop')]},
        ),
    ]
